(function(){'use strict';
const media=document.getElementById('media'),input=document.getElementById('media-files'),queue=document.getElementById('queue'),status=document.getElementById('player-status');
let urls=[],current=-1,context,analyser,bins;
function select(i){if(!urls[i])return;current=i;media.pause();media.src=urls[i].url;media.hidden=false;document.getElementById('now-playing').textContent=urls[i].name;status.textContent='Готово к воспроизведению';[...queue.children].forEach((b,n)=>b.setAttribute('aria-pressed',String(n===i)));media.load();}
input.addEventListener('change',()=>{media.pause();media.removeAttribute('src');media.load();urls.forEach(x=>URL.revokeObjectURL(x.url));urls=[...input.files].filter(f=>/^(audio|video)\//.test(f.type)).map(f=>({url:URL.createObjectURL(f),name:f.name}));queue.replaceChildren();urls.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.textContent=x.name;b.onclick=()=>select(i);queue.appendChild(b);});if(urls.length)select(0);else{media.hidden=true;status.textContent='Выберите аудио или видео.';}});
media.addEventListener('play',()=>{try{if(!context){context=new (window.AudioContext||window.webkitAudioContext)();analyser=context.createAnalyser();analyser.fftSize=256;bins=new Uint8Array(analyser.frequencyBinCount);context.createMediaElementSource(media).connect(analyser);analyser.connect(context.destination);}context.resume().catch(()=>{});}catch(e){}status.textContent='Сейчас играет';});
media.addEventListener('pause',()=>{status.textContent='Пауза';});media.addEventListener('error',()=>{status.textContent='Формат не поддерживается браузером. Попробуйте MP3 или MP4 (H.264).';});media.addEventListener('ended',()=>{status.textContent='Воспроизведение завершено';if(current+1<urls.length)select(current+1);});
const canvas=document.getElementById('sound-space'),toggle=document.getElementById('motion'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let enabled=!reduced.matches,visible=true,raf=0,gl;
function label(){toggle.setAttribute('aria-pressed',String(enabled));toggle.textContent='3D: '+(enabled?'включено':'выключено');}label();
try{gl=canvas.getContext('webgl',{alpha:true,antialias:false,powerPreference:'low-power'});}catch(e){}
if(!gl){toggle.textContent='Статичная графика';toggle.disabled=true;return;}
function shader(type,code){const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error('shader');return s;}
let program,vs,fs;try{vs=shader(gl.VERTEX_SHADER,'attribute vec3 p;uniform float t,a,ratio;varying float depth;void main(){float r=t*.12;vec3 q=p*(1.+a*.25+sin(p.y*8.+t)*.04);q.xz=mat2(cos(r),-sin(r),sin(r),cos(r))*q.xz;q.xy=mat2(.94,-.34,.34,.94)*q.xy;float d=3.0-q.z;gl_Position=vec4((q.x*1.6/d+.42)/ratio,q.y*1.6/d,0.,1.);gl_PointSize=2.5+2.0/d+a*2.;depth=(q.z+1.5)/3.;}');fs=shader(gl.FRAGMENT_SHADER,'precision mediump float;varying float depth;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;gl_FragColor=vec4(.65+depth*.25,.38+depth*.3,1.,(.2+depth*.65)*(1.-d*2.));}');program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error('link');}catch(e){toggle.disabled=true;toggle.textContent='Статичная графика';return;}
gl.useProgram(program);const points=[];const count=innerWidth<760?1600:4800;for(let i=0;i<count;i++){const y=1-2*i/(count-1),r=Math.sqrt(1-y*y),theta=i*2.399963;points.push(Math.cos(theta)*r,y,Math.sin(theta)*r);}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(points),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);const ut=gl.getUniformLocation(program,'t'),ua=gl.getUniformLocation(program,'a'),ur=gl.getUniformLocation(program,'ratio');
function resize(){const d=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(canvas.clientWidth*d);canvas.height=Math.round(canvas.clientHeight*d);gl.viewport(0,0,canvas.width,canvas.height);}resize();
function draw(t){raf=0;if(!enabled||!visible||document.hidden)return;let amplitude=0;if(analyser&&!media.paused){analyser.getByteFrequencyData(bins);amplitude=bins.reduce((a,b)=>a+b,0)/bins.length/255;}gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform1f(ut,t/1000);gl.uniform1f(ua,amplitude);gl.uniform1f(ur,canvas.width/canvas.height);gl.drawArrays(gl.POINTS,0,count);raf=requestAnimationFrame(draw);}
function start(){if(!raf&&enabled&&visible&&!document.hidden)raf=requestAnimationFrame(draw);}toggle.onclick=()=>{enabled=!enabled;label();canvas.hidden=!enabled;if(!enabled){cancelAnimationFrame(raf);raf=0;}else{resize();start();}};document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else start();});window.addEventListener('resize',resize);if('IntersectionObserver'in window)new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(!visible){cancelAnimationFrame(raf);raf=0;}else start();}).observe(canvas.parentElement);canvas.hidden=!enabled;start();window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);raf=0;media.pause();});window.addEventListener('pageshow',start);
})();
