/* Perspective film ribbon: native Canvas2D, no continuous idle rendering. */
(function(){'use strict';var base=new URL('../../img/acting/',document.currentScript.src).href;
function Film(canvas,options){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:true});if(!this.ctx)throw Error('Canvas unavailable');this.options=options||{};this.images=[];this.dead=false;var self=this;['film-revizory.webp','film-rezervatsiya.webp','film-samogon.webp'].forEach(function(file){var im=new Image();im.onload=function(){if(!self.dead&&self.last)self.render(self.last[0],self.last[1],self.last[2]);};im.src=base+file;self.images.push(im);});this.resize();}
Film.prototype.resize=function(){var d=Math.min(devicePixelRatio||1,1.25);var rect=this.options.local?this.canvas.parentElement.getBoundingClientRect():null;this.w=rect?rect.width:innerWidth;this.h=rect?rect.height:innerHeight;this.canvas.width=Math.round(this.w*d);this.canvas.height=Math.round(this.h*d);this.ctx.setTransform(d,0,0,d,0,0);};
Film.prototype.render=function(t,power,travel){if(this.dead)return;this.last=[t,power,travel];var c=this.ctx,w=this.w,h=this.h;c.clearRect(0,0,w,h);if(power<.005)return;c.save();c.globalAlpha=Math.min(1,power);var glow=c.createRadialGradient(w*(.05+.9*Math.abs(Math.sin(t*.18))),h*.65,0,w*.1,h*.65,w*.75);glow.addColorStop(0,'rgba(202,83,42,.09)');glow.addColorStop(.5,'rgba(90,20,30,.025)');glow.addColorStop(1,'rgba(20,0,0,0)');c.fillStyle=glow;c.fillRect(0,0,w,h);
var self=this,frames=[];function project(x,y,z){var f=850/(850+z);return {x:w*.5+x*f,y:h*.5+y*f};}
for(var i=0;i<12;i++){var z=((i*230-t*220)%2760+2760)%2760-160,theta=i*.39+t*.18,x=Math.sin(theta)*w*.76+(travel?Math.sin(t)*w*.2:0),y=(i%2?1:-1)*h*.42+Math.cos(theta)*h*.26;frames.push({i:i,z:z,x:x,y:y,angle:theta*.4-.5});}frames.sort(function(a,b){return b.z-a.z;});frames.forEach(function(f){var fw=210,fh=330,cos=Math.cos(f.angle),sin=Math.sin(f.angle);function pt(x,y){return project(f.x+x*cos-y*sin,f.y+x*sin+y*cos,f.z+x*.6);}var p=[pt(-fw/2,-fh/2),pt(fw/2,-fh/2),pt(fw/2,fh/2),pt(-fw/2,fh/2)];c.save();c.globalAlpha=Math.min(.65,(travel?.9:.3))*power;c.beginPath();p.forEach(function(q,j){j?c.lineTo(q.x,q.y):c.moveTo(q.x,q.y);});c.closePath();c.fillStyle='#190b0d';c.fill();c.strokeStyle='#eb9562';c.lineWidth=.65;c.stroke();var im=self.images[f.i%self.images.length];if(travel&&im.complete&&im.naturalWidth){c.save();c.clip();var sx=(p[1].x-p[0].x)/im.naturalWidth,sy=(p[1].y-p[0].y)/im.naturalWidth,tx=(p[3].x-p[0].x)/im.naturalHeight,ty=(p[3].y-p[0].y)/im.naturalHeight;c.transform(sx,sy,tx,ty,p[0].x,p[0].y);c.globalAlpha=.65*power;c.drawImage(im,0,0);c.restore();}c.fillStyle='#dba379';for(var k=0;k<12;k++){[-1,1].forEach(function(side){var q=pt(side*(fw/2-8),-fh/2+13+k*26),r=850/(850+f.z);c.fillRect(q.x,q.y,4*r,9*r);});}c.restore();});
// Deterministic dust moves only as the visitor scrolls.
c.fillStyle='#f1bb91';for(var n=0;n<30;n++){var xx=((Math.sin(n*57.3)*.5+.5)*w+t*(n%3+1)*4)%w,yy=((Math.cos(n*21.7)*.5+.5)*h-t*8)%h;c.globalAlpha=(.04+(n%5)*.016)*power;c.fillRect(xx,yy,1+(n%2),1+(n%2));}c.restore();};
Film.prototype.dispose=function(){this.dead=true;this.images.forEach(function(im){im.onload=null;});this.images=[];this.canvas.width=1;this.canvas.height=1;this.canvas.remove();};window.EekleraFilm=Film;
})();
