(function(){'use strict';var body=document.body,videoDialog=document.querySelector('.act-video-dialog'),photoDialog=document.querySelector('.act-photo-dialog'),video=videoDialog.querySelector('video'),opener=null;var videoError=videoDialog.querySelector('.video-error');
function plain(e){return !e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey&&e.button===0;}
document.querySelectorAll('[data-video]').forEach(function(a){a.addEventListener('click',function(e){if(!plain(e)||typeof videoDialog.showModal!=='function')return;e.preventDefault();opener=a;videoError.hidden=true;videoDialog.showModal();video.src=a.href;video.play().catch(function(){/* Native controls remain available if autoplay is denied. */});});});
video.addEventListener('error',function(){if(videoDialog.open)videoError.hidden=false;});videoDialog.addEventListener('close',function(){video.pause();video.removeAttribute('src');video.load();if(opener)opener.focus({preventScroll:true});});
document.querySelectorAll('[data-photo]').forEach(function(a){a.addEventListener('click',function(e){if(!plain(e)||typeof photoDialog.showModal!=='function')return;e.preventDefault();opener=a;photoDialog.querySelector('img').src=a.href;photoDialog.querySelector('img').alt=a.querySelector('img').alt;photoDialog.querySelector('p').textContent=a.querySelector('img').alt;photoDialog.showModal();});});photoDialog.addEventListener('close',function(){if(opener)opener.focus({preventScroll:true});});document.querySelectorAll('dialog [data-close]').forEach(function(b){b.onclick=function(){b.closest('dialog').close();};});
var rows=Array.from(document.querySelectorAll('.credit-row')),filters=Array.from(document.querySelectorAll('[data-filter]')),count=document.querySelector('[data-result-count]');document.querySelector('.credit-toolbar').hidden=false;
function filter(value){var total=0;rows.forEach(function(row){var show=value==='all'||(value==='archive'?Number(row.dataset.year)<2025:row.dataset.year===value);row.hidden=!show;if(show)total++;});filters.forEach(function(b){b.setAttribute('aria-pressed',String(b.dataset.filter===value));});count.textContent='Показано: '+total+' из '+rows.length;}
filters.forEach(function(b){b.onclick=function(){filter(b.dataset.filter);};});document.querySelectorAll('.role-link').forEach(function(a){a.addEventListener('click',function(){filter('all');});});function revealHash(){if(location.hash.indexOf('#credit-')===0)filter('all');}window.addEventListener('hashchange',revealHash);revealHash();
var media=matchMedia('(min-width:1101px) and (hover:hover) and (pointer:fine)'),reduced=matchMedia('(prefers-reduced-motion:reduce)'),saved=null;try{saved=localStorage.getItem('eeklera-effects');}catch(e){}var preference=saved==='on'||(saved!=='off'&&!reduced.matches),enabled=false,canvas=null,film=null,cursor=null,typography=null,raf=0;
var toggle=document.querySelector('.act-motion'),hero=document.querySelector('.act-hero'),heroCopy=document.querySelector('.act-hero-copy'),portrait=document.querySelector('.act-portrait'),aperture=document.querySelector('.act-aperture'),reel=document.querySelector('.act-reel'),reelWindow=document.querySelector('.reel-window'),roles=document.querySelector('.act-roles'),track=document.querySelector('.roles-track'),windowEl=document.querySelector('.roles-window'),cards=Array.from(document.querySelectorAll('.role-card')),headings=Array.from(document.querySelectorAll('[data-letters]')),skills=Array.from(document.querySelectorAll('.skill')),education=Array.from(document.querySelectorAll('.education-list article')),castHead=document.querySelector('.cast-head'),castFull=document.querySelector('.cast-full'),contactWord=document.querySelector('.contact-word'),contactFrame=document.querySelector('.contact-frame'),chapters=Array.from(document.querySelectorAll('.act-chapters a')),chapterSections=chapters.map(function(a){return document.querySelector(a.getAttribute('href'));}),index=0,manualScrolling=false;
function clamp(x){return Math.max(0,Math.min(1,x));}function progress(el,offset){return clamp(((offset||0)-el.getBoundingClientRect().top)/Math.max(1,el.offsetHeight-innerHeight+(offset||0)));}
function render(){raf=0;if(document.hidden)return;var active=0;chapterSections.forEach(function(s,i){if(s.getBoundingClientRect().top<innerHeight*.5)active=i;});chapters.forEach(function(a,i){if(active===i)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});if(!enabled)return;var p=progress(hero),r=progress(reel,62),q=progress(roles,62),max=Math.max(0,track.scrollWidth-windowEl.clientWidth+50),position=q*(cards.length-1);index=Math.round(position);heroCopy.style.transform='translate3d('+(-p*9)+'%,'+(-p*100)+'px,0)';heroCopy.style.opacity=String(1-p*.8);portrait.style.transform='scale('+(1+p*.24)+') translate3d('+(-p*3)+'%,0,0)';aperture.style.borderTopWidth=p*innerHeight*.13+'px';aperture.style.borderBottomWidth=p*innerHeight*.13+'px';reelWindow.style.transform='perspective(1300px) translate3d('+(-r*5)+'%,0,'+(r*120)+'px) rotateY('+(10-r*16)+'deg)';track.style.transform='translate3d('+(-q*max)+'px,0,0)';cards.forEach(function(card,i){var d=i-position;card.style.transform='perspective(1200px) translate3d(0,'+(Math.min(2,Math.abs(d))*18)+'px,'+(-Math.min(3,Math.abs(d))*45)+'px) rotateY('+Math.max(-16,Math.min(16,d*9))+'deg)';});roles.style.setProperty('--role-progress',String((index+1)/cards.length));document.querySelector('[data-role-count]').textContent=String(index+1).padStart(2,'0')+' / 06';headings.forEach(function(h){var rect=h.getBoundingClientRect(),entry=clamp((innerHeight-rect.top)/(innerHeight*.7));if(typography)typography.render(h,entry,0);});skills.forEach(function(s,i){var entry=clamp((innerHeight-s.getBoundingClientRect().top-i*20)/(innerHeight*.6));s.style.setProperty('--skill-y',((1-entry)*60)+'px');s.style.setProperty('--skill-opacity',String(.3+entry*.7));});education.forEach(function(s){var entry=clamp((innerHeight-s.getBoundingClientRect().top)/(innerHeight*.65));s.style.setProperty('--edu-y',((1-entry)*65)+'px');s.style.setProperty('--edu-tilt',((1-entry)*12)+'deg');});var cr=document.querySelector('.act-casting').getBoundingClientRect(),cp=clamp((innerHeight-cr.top)/(innerHeight+cr.height));castHead.style.transform='translate3d('+(-cp*9)+'%,'+(-cp*40)+'px,0) rotate('+(-8+cp*10)+'deg)';castFull.style.transform='translate3d('+(cp*9)+'%,'+(-cp*90)+'px,50px) rotate('+(9-cp*10)+'deg)';var ct=clamp((innerHeight-document.querySelector('.act-contact').getBoundingClientRect().top)/innerHeight);contactWord.style.transform='translateX('+(-ct*16)+'%)';contactFrame.style.transform='perspective(1000px) rotateY('+(-ct*18)+'deg) rotate('+(25-ct*12)+'deg)';if(film){var hr=hero.getBoundingClientRect(),rr=roles.getBoundingClientRect(),strength=hr.bottom>0?.4:rr.top<innerHeight&&rr.bottom>0?.35:.08;film.render(scrollY/850,strength,false);}}
function schedule(){if(!raf&&!document.hidden)raf=requestAnimationFrame(render);}
function setup(){var next=preference&&media.matches;toggle.hidden=false;toggle.textContent=preference?'Выключить эффекты':'Включить эффекты';toggle.setAttribute('aria-pressed',String(preference));body.dataset.effects=preference?'on':'off';if(next!==enabled){enabled=next;body.classList.toggle('act-camera',enabled);windowEl.scrollLeft=0;if(enabled){canvas=document.createElement('canvas');canvas.className='act-film-canvas';canvas.setAttribute('aria-hidden','true');document.body.append(canvas);try{film=new EekleraFilm(canvas);}catch(e){canvas.remove();}cursor=document.createElement('div');cursor.className='act-cursor';cursor.setAttribute('aria-hidden','true');body.append(cursor);if(window.EekleraStory)typography=new EekleraStory.Typography(headings);}else{if(film){film.dispose();film=null;}if(canvas){canvas.remove();canvas=null;}if(cursor){cursor.remove();cursor=null;}if(typography){typography.dispose();typography=null;}[heroCopy,portrait,reelWindow,track,castHead,castFull,contactWord,contactFrame].concat(cards).forEach(function(el){el.style.transform='';el.style.opacity='';});aperture.style.borderTopWidth='';aperture.style.borderBottomWidth='';skills.concat(education).forEach(function(el){el.removeAttribute('style');});}}if(film)film.resize();schedule();}
toggle.onclick=function(){preference=!preference;saved=preference?'on':'off';try{localStorage.setItem('eeklera-effects',saved);}catch(e){}setup();};media.addEventListener('change',setup);reduced.addEventListener('change',function(){if(saved===null){preference=!reduced.matches;setup();}});window.addEventListener('resize',setup,{passive:true});window.addEventListener('scroll',schedule,{passive:true});document.addEventListener('visibilitychange',function(){if(document.hidden){cancelAnimationFrame(raf);raf=0;video.pause();}else schedule();});
document.querySelectorAll('[data-role-step]').forEach(function(b){b.onclick=function(){var target=Math.max(0,Math.min(cards.length-1,index+Number(b.dataset.roleStep)));if(enabled){var range=Math.max(1,roles.offsetHeight-innerHeight+62);scrollTo({top:roles.getBoundingClientRect().top+scrollY-62+target/(cards.length-1)*range,behavior:reduced.matches?'instant':'smooth'});}else{windowEl.scrollTo({left:cards[target].offsetLeft-cards[0].offsetLeft,behavior:preference&&!reduced.matches?'smooth':'instant'});index=target;}document.querySelector('[data-role-count]').textContent=String(target+1).padStart(2,'0')+' / 06';};});windowEl.addEventListener('scroll',function(){if(enabled)return;index=Math.max(0,Math.min(cards.length-1,Math.round(windowEl.scrollLeft/(cards[0].offsetWidth+24))));document.querySelector('[data-role-count]').textContent=String(index+1).padStart(2,'0')+' / 06';},{passive:true});
// Keyboard focus advances the pinned scene to the focused card.
cards.forEach(function(card,i){card.addEventListener('focusin',function(){if(!enabled)return;var range=roles.offsetHeight-innerHeight+62;scrollTo({top:roles.getBoundingClientRect().top+scrollY-62+i/(cards.length-1)*range,behavior:'instant'});});});
document.addEventListener('pointermove',function(e){if(!cursor)return;cursor.style.opacity=e.target.closest('dialog')?'0':'1';cursor.style.transform='translate3d('+(e.clientX-28)+'px,'+(e.clientY-28)+'px,0)';cursor.textContent=e.target.closest('[data-video]')?'PLAY':e.target.closest('[data-photo]')?'VIEW':e.target.closest('a')?'OPEN ↗':'';});document.addEventListener('pointerleave',function(){if(cursor)cursor.style.opacity='0';});setup();
})();
