/* Small native WebGL layer. Photographs remain accessible DOM content. No textures or network requests. */
(function(){'use strict';
function Glass(canvas){this.canvas=canvas;var gl=canvas.getContext('webgl',{alpha:true,antialias:false,premultipliedAlpha:false});if(!gl)throw Error('WebGL unavailable');this.gl=gl;this.dead=false;var self=this;this.lost=function(e){e.preventDefault();self.dead=true;canvas.style.opacity='0';};canvas.addEventListener('webglcontextlost',this.lost);
var vs='attribute vec3 aPos;attribute vec3 aBary;attribute float aSeed;uniform float uTime;uniform float uAspect;uniform float uFlight;varying vec3 vBary;varying float vLight;void main(){float angle=aSeed*6.28+uTime*(0.15+aSeed*0.3);vec3 p=aPos;float c=cos(angle),s=sin(angle);p.xy=mat2(c,-s,s,c)*p.xy;float z=mod(aSeed*8.0-uTime*0.8+uFlight*5.0,8.0)+1.5;vec2 center=vec2(sin(aSeed*41.0)*3.8,cos(aSeed*27.0)*2.8);p.xy+=center;p.x/=uAspect;gl_Position=vec4(p.xy*2.3/z,0.0,1.0);vBary=aBary;vLight=0.25+0.75*pow(abs(sin(angle+uFlight)),4.0);}';
var fs='precision mediump float;varying vec3 vBary;varying float vLight;uniform float uStrength;void main(){float edge=min(vBary.x,min(vBary.y,vBary.z));float line=1.0-smoothstep(0.0,0.018,edge);float gleam=pow(max(0.0,1.0-abs(vBary.x-vBary.y)*5.0),8.0);float a=(line*0.5+gleam*0.12+0.04*(1.0-vBary.y))*vLight*uStrength;gl_FragColor=vec4(vec3(0.48,0.85,0.95)+line*0.12,a);}';
function shader(type,source){var s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){gl.deleteShader(s);throw Error('Glass shader failed');}return s;}
this.vs=shader(gl.VERTEX_SHADER,vs);this.fs=shader(gl.FRAGMENT_SHADER,fs);this.program=gl.createProgram();gl.attachShader(this.program,this.vs);gl.attachShader(this.program,this.fs);gl.linkProgram(this.program);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw Error('Glass link failed');gl.useProgram(this.program);
var vertices=[];for(var i=0;i<32;i++){var seed=(i+.37)/32,size=.2+(i%5)*.15;[[-size,-size*.4,1,0,0],[size*.8,-size*.8,0,1,0],[size*.1,size*1.8,0,0,1]].forEach(function(v){vertices.push(v[0],v[1],0,v[2],v[3],v[4],seed);});}this.buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);[['aPos',3,0],['aBary',3,12],['aSeed',1,24]].forEach(function(a){var p=gl.getAttribLocation(self.program,a[0]);gl.enableVertexAttribArray(p);gl.vertexAttribPointer(p,a[1],gl.FLOAT,false,28,a[2]);});this.uniforms={};['uTime','uAspect','uFlight','uStrength'].forEach(function(k){self.uniforms[k]=gl.getUniformLocation(self.program,k);});gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);this.resize();}
Glass.prototype.resize=function(){if(this.dead)return;var d=Math.min(devicePixelRatio||1,1.25);this.canvas.width=Math.round(innerWidth*d);this.canvas.height=Math.round(innerHeight*d);this.gl.viewport(0,0,this.canvas.width,this.canvas.height);};
Glass.prototype.render=function(time,strength,flight){if(this.dead)return;var g=this.gl,u=this.uniforms;g.useProgram(this.program);g.clearColor(0,0,0,0);g.clear(g.COLOR_BUFFER_BIT);g.uniform1f(u.uTime,time);g.uniform1f(u.uAspect,innerWidth/innerHeight);g.uniform1f(u.uFlight,flight||0);g.uniform1f(u.uStrength,strength);g.drawArrays(g.TRIANGLES,0,96);};
Glass.prototype.dispose=function(){this.canvas.removeEventListener('webglcontextlost',this.lost);var g=this.gl;g.deleteBuffer(this.buffer);g.deleteProgram(this.program);g.deleteShader(this.vs);g.deleteShader(this.fs);var ext=g.getExtension('WEBGL_lose_context');if(ext)ext.loseContext();this.dead=true;this.canvas.remove();};window.EekleraGlass=Glass;
})();
