(function(){'use strict';
var links=Array.from(document.querySelectorAll('[data-gallery]')),box=document.querySelector('.model-lightbox'),booking=document.querySelector('.model-booking'),current=0,opener=null;
function close(d){d.close();if(opener)opener.focus({preventScroll:true});}
document.querySelectorAll('dialog').forEach(function(d){d.querySelector('[data-close]').addEventListener('click',function(){close(d);});d.addEventListener('click',function(e){if(e.target===d)close(d);});});
var thumbs=box.querySelector('.lightbox-thumbs');links.forEach(function(a,i){var b=document.createElement('button');b.type='button';b.setAttribute('aria-label','Фото '+(i+1)+': '+a.dataset.caption);var im=document.createElement('img');im.src=a.getAttribute('href').replace('.webp','-thumb.webp');im.alt='';im.loading='lazy';b.append(im);b.addEventListener('click',function(){show(i);});thumbs.append(b);a.addEventListener('click',function(e){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||e.button!==0||typeof box.showModal!=='function')return;e.preventDefault();opener=a;show(i);box.showModal();});});
function show(i){current=(i+links.length)%links.length;var a=links[current],im=box.querySelector('.lightbox-image');im.src=a.href;im.alt=a.querySelector('img').alt;box.querySelector('#lightbox-title').textContent=a.dataset.caption;box.querySelector('[data-counter]').textContent=String(current+1).padStart(2,'0')+' / '+String(links.length).padStart(2,'0');Array.from(thumbs.children).forEach(function(b,n){b.setAttribute('aria-current',String(n===current));});}
box.querySelector('[data-prev]').onclick=function(){show(current-1);};box.querySelector('[data-next]').onclick=function(){show(current+1);};box.addEventListener('keydown',function(e){if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();show(current+(e.key==='ArrowRight'?1:-1));}});
document.querySelectorAll('[data-contact]').forEach(function(a){a.addEventListener('click',function(e){if(e.ctrlKey||e.metaKey||e.shiftKey||e.altKey||typeof booking.showModal!=='function')return;e.preventDefault();opener=a;booking.showModal();});});
var form=document.querySelector('#booking-form'),draft=booking.querySelector('.draft');form.addEventListener('submit',function(e){e.preventDefault();if(!form.reportValidity())return;var data=new FormData(form),text='Здравствуйте! Хочу обсудить проект с EEKLERA.\n\n'+[['Тип проекта','type'],['Бренд / компания','brand'],['Дата','date'],['Город','city'],['Бюджет','budget'],['Обратная связь','reply'],['Сообщение','message']].map(function(pair){return pair[0]+': '+(data.get(pair[1])||'Не указан');}).join('\n');draft.querySelector('textarea').value=text;draft.querySelector('[data-mail]').href='mailto:eeklera.advertising52@gmail.com?subject='+encodeURIComponent('EEKLERA / '+data.get('type'))+'&body='+encodeURIComponent(text);form.hidden=true;draft.hidden=false;draft.querySelector('[data-mail]').focus();});
draft.querySelector('[data-edit]').onclick=function(){form.hidden=false;draft.hidden=true;form.querySelector('select').focus();};draft.querySelector('[data-copy]').onclick=async function(){var t=draft.querySelector('textarea'),status=draft.querySelector('[data-copy-status]');try{await navigator.clipboard.writeText(t.value);status.textContent='Текст скопирован.';}catch(e){t.focus();t.select();status.textContent='Текст выделен. Нажмите Ctrl+C или выберите «Копировать».';}};
var rail=document.querySelector('.photo-rail');document.querySelectorAll('[data-rail]').forEach(function(b){b.onclick=function(){rail.scrollBy({left:Number(b.dataset.rail)*rail.clientWidth*.8,behavior:document.body.dataset.effects==='on'?'smooth':'auto'});};});
var drag=null,moved=false;rail.addEventListener('pointerdown',function(e){if(e.pointerType!=='mouse'||e.button!==0)return;drag={x:e.clientX,left:rail.scrollLeft};moved=false;});window.addEventListener('pointermove',function(e){if(!drag)return;var dx=e.clientX-drag.x;if(Math.abs(dx)>7){moved=true;rail.classList.add('is-dragging');rail.scrollLeft=drag.left-dx;}});function stopDrag(){drag=null;rail.classList.remove('is-dragging');}window.addEventListener('pointerup',stopDrag);window.addEventListener('pointercancel',stopDrag);rail.addEventListener('dragstart',function(e){e.preventDefault();});rail.addEventListener('click',function(e){if(moved){e.preventDefault();e.stopImmediatePropagation();moved=false;}},true);
document.querySelectorAll('.parameter-photo .photo,.runway-thumbs .photo,.photo-rail .photo').forEach(function(a){a.addEventListener('pointermove',function(e){if(!enabled||drag)return;var r=a.getBoundingClientRect();a.style.setProperty('--ry',((e.clientX-r.left)/r.width-.5)*7+'deg');a.style.setProperty('--rx',-((e.clientY-r.top)/r.height-.5)*7+'deg');});a.addEventListener('pointerleave',function(){a.style.removeProperty('--rx');a.style.removeProperty('--ry');});});
// Motion is optional and has no effect on access to content.
var media=matchMedia('(min-width:1101px) and (hover:hover) and (pointer:fine)'),reduced=matchMedia('(prefers-reduced-motion:reduce)'),toggle=document.querySelector('.model-motion'),saved=null,enabled=false,glass=null,canvas=null,cursor=null,raf=0;
try{saved=localStorage.getItem('eeklera-effects');}catch(e){}var preference=saved==='on'||(saved!=='off'&&!reduced.matches);toggle.hidden=false;
var hero=document.querySelector('.model-hero'),portrait=document.querySelector('.hero-portrait'),copy=document.querySelector('.hero-copy'),flash=document.querySelector('.hero-flash'),editorial=document.querySelector('.editorial-scene'),cards=Array.from(document.querySelectorAll('.editorial-photos .photo')),scenes=Array.from(document.querySelectorAll('[data-scene]'));
function clamp(v){return Math.max(0,Math.min(1,v));}function progress(el){return clamp(-el.getBoundingClientRect().top/Math.max(1,el.offsetHeight-innerHeight));}
function paint(){raf=0;if(!enabled||document.hidden)return;var p=progress(hero),q=progress(editorial);portrait.style.transform='translate3d('+(-p*7)+'%,0,0) scale('+(1+p*.3)+')';copy.style.transform='translate3d('+(-p*12)+'%, '+(-p*100)+'px, 0)';copy.style.opacity=String(1-p*.85);flash.style.opacity=String(Math.max(0,1-Math.abs(p-.85)*9)*.15);cards.forEach(function(a,i){var x=[-12,3,20][i]+q*[-12,-4,-35][i],y=[7,20,35][i]-q*[18,25,38][i],r=[-8,4,10][i]+q*[9,-9,-14][i],scale=[1,.83,.7][i]+q*[.1,.1,.2][i];a.style.transform='translate3d('+x+'%, '+y+'%, '+(q*80-i*30)+'px) rotate('+r+'deg) scale('+scale+')';});scenes.forEach(function(s){var r=s.getBoundingClientRect(),v=clamp((innerHeight-r.top)/(innerHeight*.85));s.style.setProperty('--float',((1-v)*70)+'px');s.style.setProperty('--reveal',String(.25+v*.75));s.style.setProperty('--tilt',((1-v)*8)+'deg');s.style.setProperty('--drift',((1-v)*-55)+'px');});if(glass){var er=editorial.getBoundingClientRect(),accent=er.top<innerHeight&&er.bottom>0?.5:hero.getBoundingClientRect().bottom>0?.65:.14;glass.render(scrollY/500,accent,Math.sin(scrollY/900)*.3);};}
function schedule(){if(enabled&&!raf&&!document.hidden)raf=requestAnimationFrame(paint);}
function setup(){enabled=preference&&media.matches;document.body.dataset.effects=preference?'on':'off';toggle.setAttribute('aria-pressed',String(preference));toggle.textContent=preference?'Выключить эффекты':'Включить эффекты';document.body.classList.toggle('model-camera',enabled);if(enabled&&!canvas){canvas=document.createElement('canvas');canvas.className='model-glass';canvas.setAttribute('aria-hidden','true');document.body.append(canvas);try{glass=new window.EekleraGlass(canvas);}catch(e){canvas.remove();}cursor=document.createElement('div');cursor.className='model-cursor';cursor.setAttribute('aria-hidden','true');document.body.append(cursor);}if(!enabled){cancelAnimationFrame(raf);raf=0;if(glass){glass.dispose();glass=null;}if(canvas){canvas.remove();canvas=null;}if(cursor){cursor.remove();cursor=null;}[portrait,copy,flash].concat(cards).forEach(function(el){el.style.transform='';el.style.opacity='';});scenes.forEach(function(s){['--float','--reveal','--tilt','--drift'].forEach(function(k){s.style.removeProperty(k);});});}if(glass)glass.resize();schedule();}
toggle.onclick=function(){preference=!preference;saved=preference?'on':'off';try{localStorage.setItem('eeklera-effects',preference?'on':'off');}catch(e){}setup();};media.addEventListener('change',setup);reduced.addEventListener('change',function(){if(saved===null){preference=!reduced.matches;setup();}});window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',setup,{passive:true});document.addEventListener('visibilitychange',schedule);document.addEventListener('pointermove',function(e){if(!cursor)return;if(e.target.closest('dialog')){cursor.style.opacity='0';return;}cursor.style.opacity='1';cursor.style.transform='translate3d('+(e.clientX-25)+'px,'+(e.clientY-25)+'px,0)';cursor.textContent=e.target.closest('[data-gallery]')?'VIEW':e.target.closest('a')?'OPEN ↗':e.target.closest('.photo-rail')?'DRAG':'';});document.addEventListener('pointerdown',function(){if(cursor)cursor.classList.add('is-down');});document.addEventListener('pointerup',function(){if(cursor)cursor.classList.remove('is-down');});document.addEventListener('pointerleave',function(){if(cursor)cursor.style.opacity='0';});setup();
})();
